# Generated by Django 5.1.7 on 2025-03-06 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=45)),
                ('data_nascimento', models.DateField()),
                ('observação', models.CharField(max_length=45)),
                ('pf_ou_pj', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'professor',
            },
        ),
        migrations.CreateModel(
            name='Solicitao',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=45)),
                ('parecer_coordenação', models.TextField()),
                ('parecer_secretaria', models.TextField()),
                ('parecer_compras', models.TextField()),
                ('pendências', models.TextField()),
                ('evento_sige', models.CharField(max_length=45)),
                ('processo', models.CharField(max_length=45)),
                ('solicitante', models.CharField(max_length=45)),
                ('data_inicio', models.DateField()),
                ('data_término', models.DateField()),
                ('horário_inicio', models.TimeField()),
                ('horário_término', models.TimeField()),
                ('carga_horaria', models.IntegerField()),
                ('valor_hora', models.FloatField()),
                ('prestador', models.CharField(max_length=45)),
                ('curso_treinamento', models.CharField(max_length=45)),
                ('serviço', models.TextField()),
                ('observação', models.TextField()),
            ],
            options={
                'db_table': 'solicitação',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('número_telefone', models.CharField(max_length=45)),
                ('senha', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='ControlePagamento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('situação_pasta', models.CharField(max_length=45)),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField()),
                ('modalidade', models.CharField(max_length=45)),
                ('curso_componentes', models.CharField(max_length=45)),
                ('evento', models.CharField(max_length=45)),
                ('solicitante', models.CharField(max_length=45)),
                ('fornecedor', models.CharField(max_length=45)),
                ('valor_sc', models.FloatField()),
                ('total_horas_contradas', models.IntegerField()),
                ('valor_hora_aula', models.FloatField()),
                ('valor_pago', models.FloatField()),
                ('saldo', models.FloatField()),
                ('saldo_de_horas', models.IntegerField()),
                ('horas_pagas', models.IntegerField()),
                ('prazo_validade_contrato', models.DateField()),
                ('observação', models.TextField()),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.professor')),
                ('solicitação', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.solicitao', unique=True)),
            ],
            options={
                'db_table': 'controle_pagamento',
                'unique_together': {('id', 'solicitação', 'professor')},
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.usuario')),
            ],
            options={
                'db_table': 'login',
                'unique_together': {('id', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('solicitação', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='website.solicitao')),
                ('controle_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.controlepagamento')),
                ('controle_pagamento_solicitação', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='relatrio_controle_pagamento_solicitação_set', to='website.controlepagamento', to_field='solicitação_id')),
            ],
            options={
                'db_table': 'relatório',
                'unique_together': {('solicitação', 'controle_pagamento', 'controle_pagamento_solicitação')},
            },
        ),
    ]
