# Generated by Django 5.1.7 on 2025-03-23 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=45)),
                ('data_nascimento', models.DateField()),
                ('observacao', models.CharField(max_length=45)),
                ('pf_ou_pj', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=15)),
            ],
            options={
                'db_table': 'professor',
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=45)),
                ('parecer_coordenacao', models.TextField()),
                ('parecer_secretaria', models.TextField()),
                ('parecer_compras', models.TextField()),
                ('pendencias', models.TextField()),
                ('evento_sige', models.CharField(max_length=45)),
                ('processo', models.CharField(max_length=45)),
                ('solicitante', models.CharField(max_length=45)),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField()),
                ('horario_inicio', models.TimeField()),
                ('horario_termino', models.TimeField()),
                ('carga_horaria', models.IntegerField()),
                ('valor_hora', models.FloatField()),
                ('prestador', models.CharField(max_length=45)),
                ('curso_treinamento', models.CharField(max_length=45)),
                ('servico', models.TextField()),
                ('observacao', models.TextField()),
            ],
            options={
                'db_table': 'solicitacao',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=255)),
                ('numero_telefone', models.CharField(max_length=45)),
                ('senha', models.CharField(default='', max_length=45)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='ControlePagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao_pasta', models.CharField(max_length=45)),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField()),
                ('modalidade', models.CharField(max_length=45)),
                ('curso_componentes', models.CharField(max_length=45)),
                ('evento', models.CharField(max_length=45)),
                ('solicitante', models.CharField(max_length=45)),
                ('fornecedor', models.CharField(max_length=45)),
                ('valor_sc', models.FloatField()),
                ('total_horas_contradas', models.IntegerField()),
                ('valor_hora_aula', models.FloatField()),
                ('valor_pago', models.FloatField()),
                ('saldo', models.FloatField()),
                ('saldo_de_horas', models.IntegerField()),
                ('horas_pagas', models.IntegerField()),
                ('prazo_validade_contrato', models.DateField()),
                ('observacao', models.TextField()),
                ('professor', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='website.professor')),
                ('solicitacao', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='website.solicitacao')),
            ],
            options={
                'db_table': 'controle_pagamento',
                'unique_together': {('id', 'solicitacao', 'professor')},
            },
        ),
    ]
