# Generated by Django 5.1.7 on 2025-03-23 23:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=255, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numero_telefone',
            field=models.CharField(max_length=45, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default='', max_length=512),
        ),
    ]
