# Generated by Django 4.2.20 on 2025-03-13 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_delete_login"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="controlepagamento",
            options={},
        ),
        migrations.AlterModelOptions(
            name="professor",
            options={},
        ),
        migrations.AlterModelOptions(
            name="solicitao",
            options={},
        ),
        migrations.AlterModelOptions(
            name="usuario",
            options={},
        ),
    ]
