# Generated by Django 5.1.7 on 2025-03-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_professor_cnpj_professor_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='observacao',
            field=models.TextField(),
        ),
    ]
