# Generated by Django 5.1.7 on 2025-03-17 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_controlepagamento_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Solicitao',
            new_name='Solicitacao',
        ),
        migrations.RenameField(
            model_name='controlepagamento',
            old_name='observação',
            new_name='observacao',
        ),
        migrations.RenameField(
            model_name='controlepagamento',
            old_name='situação_pasta',
            new_name='situacao_pasta',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='observação',
            new_name='observacao',
        ),
        migrations.RenameField(
            model_name='solicitacao',
            old_name='data_término',
            new_name='data_termino',
        ),
        migrations.RenameField(
            model_name='solicitacao',
            old_name='horário_inicio',
            new_name='horario_inicio',
        ),
        migrations.RenameField(
            model_name='solicitacao',
            old_name='horário_término',
            new_name='horario_termino',
        ),
        migrations.RenameField(
            model_name='solicitacao',
            old_name='observação',
            new_name='observacao',
        ),
        migrations.RenameField(
            model_name='solicitacao',
            old_name='parecer_coordenação',
            new_name='parecer_coordenacao',
        ),
        migrations.RenameField(
            model_name='solicitacao',
            old_name='pendências',
            new_name='pendencias',
        ),
        migrations.RenameField(
            model_name='solicitacao',
            old_name='serviço',
            new_name='servico',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='número_telefone',
            new_name='numero_telefone',
        ),
        migrations.AddField(
            model_name='controlepagamento',
            name='professor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='website.professor'),
        ),
        migrations.AddField(
            model_name='controlepagamento',
            name='solicitacao',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='website.solicitacao'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='professor',
            name='pf_ou_pj',
            field=models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='controlepagamento',
            unique_together={('id', 'solicitacao', 'professor')},
        ),
        migrations.AlterModelTable(
            name='solicitacao',
            table='solicitacao',
        ),
    ]
