# Generated by Django 5.2 on 2025-04-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_solicitacao_pdf_alter_solicitacao_curso_treinamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlepagamento',
            name='modalidade',
            field=models.CharField(default='hora-aula', max_length=45),
        ),
    ]
