# Generated by Django 5.2 on 2025-04-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_controlepagamento_modalidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processo', models.CharField(max_length=255)),
                ('evento', models.DateField()),
                ('prestador', models.CharField(max_length=255)),
                ('servico', models.CharField(max_length=255)),
                ('componentes', models.CharField(max_length=255)),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField()),
                ('carga_horaria', models.IntegerField()),
                ('valor_hora_aula', models.FloatField()),
            ],
        ),
    ]
