# Generated by Django 5.2 on 2025-04-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_contratos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='pdf',
        ),
        migrations.AddField(
            model_name='contratos',
            name='pdf',
            field=models.FileField(default=None, upload_to='contratos/hora-aula/'),
        ),
    ]
