# Generated by Django 5.2 on 2025-04-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_solicitacao_pdf_contratos_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='pdf',
            field=models.FileField(null=True, upload_to='contratos/hora-aula/'),
        ),
    ]
