# Generated by Django 5.2 on 2025-04-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_contratos_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='contratos/hora-aula/'),
        ),
    ]
