# Generated by Django 5.2 on 2025-04-05 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_contratos_pdf'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contratos',
            table='contratos',
        ),
    ]
