# Generated by Django 5.2 on 2025-04-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_contratos_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='modalidade',
            field=models.CharField(default='Hora-aula', max_length=50),
        ),
        migrations.DeleteModel(
            name='ControlePagamento',
        ),
        migrations.DeleteModel(
            name='Solicitacao',
        ),
    ]
