# Generated by Django 5.2 on 2025-04-16 16:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_contratos_modalidade_delete_controlepagamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='modalidade',
            field=models.CharField(choices=[('hora-aula', 'Hora-aula')], default='hora-aula', max_length=50),
        ),
        migrations.AlterField(
            model_name='professor',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{2}\\.?(\\d{3}\\.?){2}/?\\d{4}-?\\d{2}$')]),
        ),
        migrations.AlterField(
            model_name='professor',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(regex='\\d{3}\\.?\\d{3}\\.?\\d{3}-?\\d{2}$')]),
        ),
    ]
