# Generated by Django 5.2 on 2025-04-19 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_contratos_modalidade_alter_professor_cnpj_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratos',
            name='pdf',
        ),
    ]
