# Generated by Django 5.2 on 2025-04-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_remove_contratos_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='contratos/hora-aula/'),
        ),
    ]
