# Generated by Django 5.2 on 2025-04-20 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_contratos_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratos',
            name='pdf',
        ),
    ]
