# Generated by Django 5.2 on 2025-04-23 21:06

import django.core.validators
import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_remove_contratos_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{2}\\.?(\\d{3}\\.?){2}/?\\d{4}-?\\d{2}$'), website.models.Professor.verify_cnpj]),
        ),
        migrations.AlterField(
            model_name='professor',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(regex='\\d{3}\\.?\\d{3}\\.?\\d{3}-?\\d{2}$'), website.models.Professor.verify_cpf]),
        ),
    ]
