-- MySQL Script generated by MySQL Workbench
-- Mon Mar 10 15:25:00 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_controleextraquadro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_controleextraquadro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_controleextraquadro` ;
USE `db_controleextraquadro` ;

-- -----------------------------------------------------
-- Table `db_controleextraquadro`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_controleextraquadro`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `número_telefone` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_controleextraquadro`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_controleextraquadro`.`professor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `observação` VARCHAR(45) NOT NULL,
  `pf_ou_pj` ENUM("Pessoa Física", "Pessoa Jurídica") NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_controleextraquadro`.`solicitação`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_controleextraquadro`.`solicitação` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  `parecer_coordenação` TEXT NOT NULL,
  `parecer_secretaria` TEXT NOT NULL,
  `parecer_compras` TEXT NOT NULL,
  `pendências` TEXT NOT NULL,
  `evento_sige` VARCHAR(45) NOT NULL,
  `processo` VARCHAR(45) NOT NULL,
  `solicitante` VARCHAR(45) NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_término` DATE NOT NULL,
  `horário_inicio` TIME NOT NULL,
  `horário_término` TIME NOT NULL,
  `carga_horaria` INT NOT NULL,
  `valor_hora` DOUBLE NOT NULL,
  `prestador` VARCHAR(45) NOT NULL,
  `curso_treinamento` VARCHAR(45) NOT NULL,
  `serviço` TEXT NOT NULL,
  `observação` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_controleextraquadro`.`controle_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_controleextraquadro`.`controle_pagamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `situação_pasta` VARCHAR(45) NOT NULL,
  `solicitação_id` INT NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_termino` DATE NOT NULL,
  `modalidade` VARCHAR(45) NOT NULL,
  `curso_componentes` VARCHAR(45) NOT NULL,
  `evento` VARCHAR(45) NOT NULL,
  `solicitante` VARCHAR(45) NOT NULL,
  `fornecedor` VARCHAR(45) NOT NULL,
  `valor_sc` DOUBLE NOT NULL,
  `total_horas_contradas` INT NOT NULL,
  `valor_hora_aula` DOUBLE NOT NULL,
  `valor_pago` DOUBLE NOT NULL,
  `saldo` DOUBLE NOT NULL,
  `saldo_de_horas` INT NOT NULL,
  `horas_pagas` INT NOT NULL,
  `prazo_validade_contrato` DATE NOT NULL,
  `observação` TEXT NOT NULL,
  `professor_id` INT NOT NULL,
  PRIMARY KEY (`id`, `solicitação_id`, `professor_id`),
  INDEX `fk_controle_pagamento_solicitação1_idx` (`solicitação_id` ASC) VISIBLE,
  INDEX `fk_controle_pagamento_professor1_idx` (`professor_id` ASC) VISIBLE,
  CONSTRAINT `fk_controle_pagamento_solicitação1`
    FOREIGN KEY (`solicitação_id`)
    REFERENCES `db_controleextraquadro`.`solicitação` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_controle_pagamento_professor1`
    FOREIGN KEY (`professor_id`)
    REFERENCES `db_controleextraquadro`.`professor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
